services:
  bt-cf-sync:
    image: ghcr.io/xzw38/bt-cf-sync:latest
    container_name: bt-cf-sync
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:25708:8080"
    volumes:
      - /www/server/panel/vhost/nginx:/bt-nginx:ro
      - ./data:/data
